name: Propuesta de mejora
description: Sugiere una funcionalidad o mejora
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema o necesidad
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
